- name: Deploy nginx on OpenShift
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Deploy nginx
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: mohamedbram-dev
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: nginxinc/nginx-unprivileged
                    ports:
                      - containerPort: 8080
